export type Event = {
  id: string
  title: string
  description: string
  date: string
  time: string
  location: string
  type: "Workshop" | "Webinar" | "Open Day"
  capacity: number
  registered: number
}

export const events: Event[] = [
  {
    id: "1",
    title: "Computer Science Open Day",
    description: "Join us for a day of exploring our Computer Science programs, meeting faculty, and touring our state-of-the-art facilities.",
    date: "2024-03-15",
    time: "10:00 AM",
    location: "Main Campus, Building A",
    type: "Open Day",
    capacity: 100,
    registered: 45,
  },
  {
    id: "2",
    title: "Web Development Workshop",
    description: "Learn modern web development techniques including React, Next.js, and TypeScript.",
    date: "2024-03-20",
    time: "2:00 PM",
    location: "Tech Lab, Building B",
    type: "Workshop",
    capacity: 30,
    registered: 25,
  },
  {
    id: "3",
    title: "AI and Machine Learning Webinar",
    description: "An introduction to artificial intelligence and machine learning concepts and applications.",
    date: "2024-03-25",
    time: "6:00 PM",
    location: "Online",
    type: "Webinar",
    capacity: 200,
    registered: 150,
  },
  {
    id: "4",
    title: "Engineering Open Day",
    description: "Discover our engineering programs and see our labs in action.",
    date: "2024-04-05",
    time: "10:00 AM",
    location: "Engineering Building",
    type: "Open Day",
    capacity: 80,
    registered: 60,
  },
  {
    id: "5",
    title: "Data Science Workshop",
    description: "Hands-on workshop covering data analysis, visualization, and machine learning basics.",
    date: "2024-04-10",
    time: "1:00 PM",
    location: "Data Lab, Building C",
    type: "Workshop",
    capacity: 25,
    registered: 20,
  },
  {
    id: "6",
    title: "Cybersecurity Webinar",
    description: "Learn about the latest trends in cybersecurity and how to protect your digital assets.",
    date: "2024-04-15",
    time: "3:00 PM",
    location: "Online",
    type: "Webinar",
    capacity: 150,
    registered: 120,
  },
  {
    id: "7",
    title: "Business School Open Day",
    description: "Explore our business programs and meet with faculty and current students.",
    date: "2024-04-20",
    time: "11:00 AM",
    location: "Business School, Main Hall",
    type: "Open Day",
    capacity: 120,
    registered: 90,
  },
  {
    id: "8",
    title: "Mobile App Development Workshop",
    description: "Build your first mobile app using React Native and modern development practices.",
    date: "2024-04-25",
    time: "2:00 PM",
    location: "Mobile Lab, Building D",
    type: "Workshop",
    capacity: 20,
    registered: 15,
  },
  {
    id: "9",
    title: "Cloud Computing Webinar",
    description: "Introduction to cloud platforms and services for modern applications.",
    date: "2024-05-01",
    time: "5:00 PM",
    location: "Online",
    type: "Webinar",
    capacity: 180,
    registered: 140,
  },
  {
    id: "10",
    title: "Arts and Design Open Day",
    description: "Experience our creative programs and see student exhibitions.",
    date: "2024-05-05",
    time: "10:00 AM",
    location: "Arts Center",
    type: "Open Day",
    capacity: 90,
    registered: 70,
  },
  {
    id: "11",
    title: "UI/UX Design Workshop",
    description: "Learn the principles of user interface and user experience design.",
    date: "2024-05-10",
    time: "1:00 PM",
    location: "Design Studio, Building E",
    type: "Workshop",
    capacity: 25,
    registered: 18,
  },
  {
    id: "12",
    title: "Blockchain Technology Webinar",
    description: "Understanding blockchain technology and its applications in various industries.",
    date: "2024-05-15",
    time: "4:00 PM",
    location: "Online",
    type: "Webinar",
    capacity: 160,
    registered: 130,
  },
  {
    id: "13",
    title: "Medical School Open Day",
    description: "Tour our medical facilities and learn about our healthcare programs.",
    date: "2024-05-20",
    time: "11:00 AM",
    location: "Medical School Complex",
    type: "Open Day",
    capacity: 70,
    registered: 55,
  },
  {
    id: "14",
    title: "Game Development Workshop",
    description: "Create your first game using Unity and C# programming.",
    date: "2024-05-25",
    time: "2:00 PM",
    location: "Game Lab, Building F",
    type: "Workshop",
    capacity: 20,
    registered: 16,
  },
  {
    id: "15",
    title: "Digital Marketing Webinar",
    description: "Learn effective digital marketing strategies for the modern business landscape.",
    date: "2024-06-01",
    time: "3:00 PM",
    location: "Online",
    type: "Webinar",
    capacity: 200,
    registered: 180,
  }
] 